// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://vbufiofpxvduoekqbsfu.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZidWZpb2ZweHZkdW9la3Fic2Z1Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjE2ODAzMjEsImV4cCI6MjA3NzI1NjMyMX0.kn9IMarPnDe0RCC_ape4g_fwegLEn5ZPHYupdl2t76I";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});